// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gywfxsepifipdsrqfuim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5d2Z4c2VwaWZpcGRzcnFmdWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTE2NDgsImV4cCI6MjA2MDAyNzY0OH0.pKrhwjl-Z8efo6YNh3V2IIDe0TpZMW9yC_p-g58TWz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);